language: node_js
node_js:
  - 6.9.5
before_script:
  - "npm i -g jasmine-node"
  - "sleep 5"
script:
  - "npm test"
  - "npm run-script coverage"
after_success:
  - "npm run-script coveralls"
env:
  global:
    - GITHUB_CLIENT_ID=test
    - GITHUB_CLIENT_SECRET=testSecret
    - SESSION_SECRET=testSessionSecret
    - GITHUB_ORG=testOrg
    - CF_CLI_VERSION=6.22.2
services:
  - mongodb
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=$CF_CLI_VERSION"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
deploy:
  - provider: script
    script: DEPLOY_ENV=dev ./deploy-travis.sh
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: DEPLOY_ENV=prod ./deploy-travis.sh
    skip_cleanup: true
    on:
      branch: master
sudo: required
