language: node_js
node_js:
    - 0.12
before_script:
    - "npm i -g jasmine-node"
    - "npm start"
script:
    - "npm test"
env:
    - GITHUB_CLIENT_ID=test GITHUB_CLIENT_SECRET=testSecret SKIP_AUTH=true
services:
  - mongodb
